info:
  myStaticInfo: whatever
  artifactid: @project.artifactId@
  version: @project.version@


management:
  shell:
    auth:
      simple:
        user:
          name: admin
          password: pass
